# Generated by Django 2.1.2 on 2018-10-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='is_hot_product',
            new_name='is_hot',
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='is_new_product',
            new_name='is_new',
        ),
    ]
