# Generated by Django 2.1.1 on 2018-10-14 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20181011_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscategorybrand',
            options={'verbose_name': '商家品牌名', 'verbose_name_plural': '商家品牌名'},
        ),
        migrations.AddField(
            model_name='goodscategorybrand',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类别'),
        ),
    ]
