# Generated by Django 2.1 on 2018-10-16 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20181014_1730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodImage',
            new_name='GoodsImage',
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
        migrations.AlterModelOptions(
            name='goodsimage',
            options={'verbose_name': '商品的图片', 'verbose_name_plural': '商品的图片'},
        ),
    ]
