# Generated by Django 2.1 on 2018-10-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20181017_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='desc',
            field=models.TextField(default='', help_text='类别描述', max_length=300, verbose_name='类别描述'),
        ),
    ]
