# Generated by Django 2.1 on 2018-11-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_auto_20181031_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='sale_price',
            new_name='shop_price',
        ),
    ]
