# Generated by Django 2.1 on 2018-10-16 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordergoods',
            options={'verbose_name': '订单中的商品详情', 'verbose_name_plural': '订单中的商品详情'},
        ),
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'verbose_name': '订单详情信息', 'verbose_name_plural': '订单详情信息'},
        ),
    ]
