# Generated by Django 2.1 on 2018-11-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20181109_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='order_amount',
            new_name='order_mount',
        ),
    ]
